# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dnac_api_client
from dnac_api_client.api.intent_application_policy_api import IntentApplicationPolicyApi  # noqa: E501
from dnac_api_client.rest import ApiException


class TestIntentApplicationPolicyApi(unittest.TestCase):
    """IntentApplicationPolicyApi unit test stubs"""

    def setUp(self):
        self.api = dnac_api_client.api.intent_application_policy_api.IntentApplicationPolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dna_intent_api_v1_application_count_get(self):
        """Test case for dna_intent_api_v1_application_count_get

        Get Applications Count  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_application_policy_get(self):
        """Test case for dna_intent_api_v1_application_policy_get

        Get Application Policies  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_application_set_count_get(self):
        """Test case for dna_intent_api_v1_application_set_count_get

        Get Application Sets Count  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_application_sets_get(self):
        """Test case for dna_intent_api_v1_application_sets_get

        Get Application Sets  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_applications_get(self):
        """Test case for dna_intent_api_v1_applications_get

        Get Applications  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_create_application_policy_post(self):
        """Test case for dna_intent_api_v1_create_application_policy_post

        Post Application Policy Intent  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_create_application_post(self):
        """Test case for dna_intent_api_v1_create_application_post

        Post Application  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_create_application_set_post(self):
        """Test case for dna_intent_api_v1_create_application_set_post

        Post Application Set  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_delete_application_delete(self):
        """Test case for dna_intent_api_v1_delete_application_delete

        Delete Application  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_delete_application_set_delete(self):
        """Test case for dna_intent_api_v1_delete_application_set_delete

        Delete Application Set  # noqa: E501
        """
        pass

    def test_dna_intent_api_v1_update_application_put(self):
        """Test case for dna_intent_api_v1_update_application_put

        Edit Application  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
