# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dnac_api_client
from dnac_api_client.api.swim_api import SWIMApi  # noqa: E501
from dnac_api_client.rest import ApiException


class TestSWIMApi(unittest.TestCase):
    """SWIMApi unit test stubs"""

    def setUp(self):
        self.api = dnac_api_client.api.swim_api.SWIMApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_image_activation_device_post(self):
        """Test case for api_v1_image_activation_device_post

        Trigger activation on a device  # noqa: E501
        """
        pass

    def test_api_v1_image_distribution_post(self):
        """Test case for api_v1_image_distribution_post

        Trigger distribution of an image  # noqa: E501
        """
        pass

    def test_api_v1_image_importation_get(self):
        """Test case for api_v1_image_importation_get

        Get image details with filter  # noqa: E501
        """
        pass

    def test_api_v1_image_importation_source_file_post(self):
        """Test case for api_v1_image_importation_source_file_post

        Import an image from local file system  # noqa: E501
        """
        pass

    def test_api_v1_image_importation_source_url_post(self):
        """Test case for api_v1_image_importation_source_url_post

        Trigger now or schedule import of an image from a URL  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
