# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dnac_api_client
from dnac_api_client.models.site_hierarchy_response import SiteHierarchyResponse  # noqa: E501
from dnac_api_client.rest import ApiException


class TestSiteHierarchyResponse(unittest.TestCase):
    """SiteHierarchyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteHierarchyResponse(self):
        """Test SiteHierarchyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dnac_api_client.models.site_hierarchy_response.SiteHierarchyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
