# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dnac_api_client
from dnac_api_client.api.networks_api import NetworksApi  # noqa: E501
from dnac_api_client.rest import ApiException


class TestNetworksApi(unittest.TestCase):
    """NetworksApi unit test stubs"""

    def setUp(self):
        self.api = dnac_api_client.api.networks_api.NetworksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_topology_l2_vlan_id_get(self):
        """Test case for api_v1_topology_l2_vlan_id_get

        getL2Topology  # noqa: E501
        """
        pass

    def test_api_v1_topology_l3_topology_type_get(self):
        """Test case for api_v1_topology_l3_topology_type_get

        getL3Topology  # noqa: E501
        """
        pass

    def test_api_v1_topology_physical_topology_get(self):
        """Test case for api_v1_topology_physical_topology_get

        getPhysicalTopology  # noqa: E501
        """
        pass

    def test_api_v1_topology_site_topology_get(self):
        """Test case for api_v1_topology_site_topology_get

        getSiteTopology  # noqa: E501
        """
        pass

    def test_api_v1_topology_vlan_vlan_names_get(self):
        """Test case for api_v1_topology_vlan_vlan_names_get

        getVlanNames  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
