# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dnac_api_client
from dnac_api_client.api.command_runner_api import CommandRunnerApi  # noqa: E501
from dnac_api_client.rest import ApiException


class TestCommandRunnerApi(unittest.TestCase):
    """CommandRunnerApi unit test stubs"""

    def setUp(self):
        self.api = dnac_api_client.api.command_runner_api.CommandRunnerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_network_device_poller_cli_legit_reads_get(self):
        """Test case for api_v1_network_device_poller_cli_legit_reads_get

        Get all keywords of CLIs accepted by command runner  # noqa: E501
        """
        pass

    def test_api_v1_network_device_poller_cli_read_request_post(self):
        """Test case for api_v1_network_device_poller_cli_read_request_post

        Run read-only commands on devices to get their real-time configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
