# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dnac_api_client
from dnac_api_client.models.client_health_response_response import ClientHealthResponseResponse  # noqa: E501
from dnac_api_client.rest import ApiException


class TestClientHealthResponseResponse(unittest.TestCase):
    """ClientHealthResponseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientHealthResponseResponse(self):
        """Test ClientHealthResponseResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dnac_api_client.models.client_health_response_response.ClientHealthResponseResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
