# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dnac_api_client
from dnac_api_client.api.path_trace_api import PathTraceApi  # noqa: E501
from dnac_api_client.rest import ApiException


class TestPathTraceApi(unittest.TestCase):
    """PathTraceApi unit test stubs"""

    def setUp(self):
        self.api = dnac_api_client.api.path_trace_api.PathTraceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_flow_analysis_flow_analysis_id_delete(self):
        """Test case for api_v1_flow_analysis_flow_analysis_id_delete

        Deletes a flow analysis request  # noqa: E501
        """
        pass

    def test_api_v1_flow_analysis_flow_analysis_id_get(self):
        """Test case for api_v1_flow_analysis_flow_analysis_id_get

        Retrieves result of a previously requested flow analysis  # noqa: E501
        """
        pass

    def test_api_v1_flow_analysis_get(self):
        """Test case for api_v1_flow_analysis_get

        Retrieves a summary of all flow analyses stored  # noqa: E501
        """
        pass

    def test_api_v1_flow_analysis_post(self):
        """Test case for api_v1_flow_analysis_post

        Initiates a new flow analysis  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
