# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ClientDetailResponseResponseTopology(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'nodes': 'list[ClientDetailResponseResponseTopologyNodes]',
        'links': 'list[ClientDetailResponseResponseTopologyLinks]'
    }

    attribute_map = {
        'nodes': 'nodes',
        'links': 'links'
    }

    def __init__(self, nodes=None, links=None):  # noqa: E501
        """ClientDetailResponseResponseTopology - a model defined in OpenAPI"""  # noqa: E501

        self._nodes = None
        self._links = None
        self.discriminator = None

        if nodes is not None:
            self.nodes = nodes
        if links is not None:
            self.links = links

    @property
    def nodes(self):
        """Gets the nodes of this ClientDetailResponseResponseTopology.  # noqa: E501


        :return: The nodes of this ClientDetailResponseResponseTopology.  # noqa: E501
        :rtype: list[ClientDetailResponseResponseTopologyNodes]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this ClientDetailResponseResponseTopology.


        :param nodes: The nodes of this ClientDetailResponseResponseTopology.  # noqa: E501
        :type: list[ClientDetailResponseResponseTopologyNodes]
        """

        self._nodes = nodes

    @property
    def links(self):
        """Gets the links of this ClientDetailResponseResponseTopology.  # noqa: E501


        :return: The links of this ClientDetailResponseResponseTopology.  # noqa: E501
        :rtype: list[ClientDetailResponseResponseTopologyLinks]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ClientDetailResponseResponseTopology.


        :param links: The links of this ClientDetailResponseResponseTopology.  # noqa: E501
        :type: list[ClientDetailResponseResponseTopologyLinks]
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientDetailResponseResponseTopology):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
