# coding: utf-8

"""
    Cisco DNA Center Platform v. 1.2.x (EFT)

    REST API (EFT)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ClientDetailResponseResponseConnectionInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'protocol': 'str',
        'spatial_stream': 'str',
        'wmm': 'str',
        'host_type': 'str',
        'channel_width': 'str',
        'nw_device_name': 'str',
        'channel': 'str',
        'nw_device_mac': 'str',
        'band': 'str',
        'uapsd': 'str',
        'timestamp': 'str'
    }

    attribute_map = {
        'protocol': 'protocol',
        'spatial_stream': 'spatialStream',
        'wmm': 'wmm',
        'host_type': 'hostType',
        'channel_width': 'channelWidth',
        'nw_device_name': 'nwDeviceName',
        'channel': 'channel',
        'nw_device_mac': 'nwDeviceMac',
        'band': 'band',
        'uapsd': 'uapsd',
        'timestamp': 'timestamp'
    }

    def __init__(self, protocol=None, spatial_stream=None, wmm=None, host_type=None, channel_width=None, nw_device_name=None, channel=None, nw_device_mac=None, band=None, uapsd=None, timestamp=None):  # noqa: E501
        """ClientDetailResponseResponseConnectionInfo - a model defined in OpenAPI"""  # noqa: E501

        self._protocol = None
        self._spatial_stream = None
        self._wmm = None
        self._host_type = None
        self._channel_width = None
        self._nw_device_name = None
        self._channel = None
        self._nw_device_mac = None
        self._band = None
        self._uapsd = None
        self._timestamp = None
        self.discriminator = None

        if protocol is not None:
            self.protocol = protocol
        if spatial_stream is not None:
            self.spatial_stream = spatial_stream
        if wmm is not None:
            self.wmm = wmm
        if host_type is not None:
            self.host_type = host_type
        if channel_width is not None:
            self.channel_width = channel_width
        if nw_device_name is not None:
            self.nw_device_name = nw_device_name
        if channel is not None:
            self.channel = channel
        if nw_device_mac is not None:
            self.nw_device_mac = nw_device_mac
        if band is not None:
            self.band = band
        if uapsd is not None:
            self.uapsd = uapsd
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def protocol(self):
        """Gets the protocol of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The protocol of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this ClientDetailResponseResponseConnectionInfo.


        :param protocol: The protocol of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._protocol = protocol

    @property
    def spatial_stream(self):
        """Gets the spatial_stream of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The spatial_stream of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._spatial_stream

    @spatial_stream.setter
    def spatial_stream(self, spatial_stream):
        """Sets the spatial_stream of this ClientDetailResponseResponseConnectionInfo.


        :param spatial_stream: The spatial_stream of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._spatial_stream = spatial_stream

    @property
    def wmm(self):
        """Gets the wmm of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The wmm of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._wmm

    @wmm.setter
    def wmm(self, wmm):
        """Sets the wmm of this ClientDetailResponseResponseConnectionInfo.


        :param wmm: The wmm of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._wmm = wmm

    @property
    def host_type(self):
        """Gets the host_type of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The host_type of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._host_type

    @host_type.setter
    def host_type(self, host_type):
        """Sets the host_type of this ClientDetailResponseResponseConnectionInfo.


        :param host_type: The host_type of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._host_type = host_type

    @property
    def channel_width(self):
        """Gets the channel_width of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The channel_width of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._channel_width

    @channel_width.setter
    def channel_width(self, channel_width):
        """Sets the channel_width of this ClientDetailResponseResponseConnectionInfo.


        :param channel_width: The channel_width of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._channel_width = channel_width

    @property
    def nw_device_name(self):
        """Gets the nw_device_name of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The nw_device_name of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._nw_device_name

    @nw_device_name.setter
    def nw_device_name(self, nw_device_name):
        """Sets the nw_device_name of this ClientDetailResponseResponseConnectionInfo.


        :param nw_device_name: The nw_device_name of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._nw_device_name = nw_device_name

    @property
    def channel(self):
        """Gets the channel of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The channel of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ClientDetailResponseResponseConnectionInfo.


        :param channel: The channel of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._channel = channel

    @property
    def nw_device_mac(self):
        """Gets the nw_device_mac of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The nw_device_mac of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._nw_device_mac

    @nw_device_mac.setter
    def nw_device_mac(self, nw_device_mac):
        """Sets the nw_device_mac of this ClientDetailResponseResponseConnectionInfo.


        :param nw_device_mac: The nw_device_mac of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._nw_device_mac = nw_device_mac

    @property
    def band(self):
        """Gets the band of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The band of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._band

    @band.setter
    def band(self, band):
        """Sets the band of this ClientDetailResponseResponseConnectionInfo.


        :param band: The band of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._band = band

    @property
    def uapsd(self):
        """Gets the uapsd of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The uapsd of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._uapsd

    @uapsd.setter
    def uapsd(self, uapsd):
        """Sets the uapsd of this ClientDetailResponseResponseConnectionInfo.


        :param uapsd: The uapsd of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._uapsd = uapsd

    @property
    def timestamp(self):
        """Gets the timestamp of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501


        :return: The timestamp of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ClientDetailResponseResponseConnectionInfo.


        :param timestamp: The timestamp of this ClientDetailResponseResponseConnectionInfo.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientDetailResponseResponseConnectionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
